### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by brucellino**
Add contributor covenant

### CODE REVIEW

**Comment by zapeachy-devpool** [comment]
Please add:
Except people who regularly enjoy reality television.
to Our Pledge.

**Comment by brucellino** [comment]
Not that I _don't_ enjoy a good :tv:, but I guess we'll update the CoC as time goes by :relieved:

**Comment by zapeachy-devpool** [comment]
Specifier is **regularly**. If only on occasion, it's ok.

**Comment by zapeachy-devpool** [comment]
accepted as is, we'll discus people who watch reality tv later...

**Pull request merged**
